### ISSUE TITLE
Framed Controller, Slave & Trim do not drop when broken, even with silk touch

### ISSUE THREAD

**Issue by Sirfirelord1** [eutro/FramedCompactDrawers#20]
Version: 1.20-6.0.0
MC: 1.20.1
Forge: 47.2.21

Basically what it says in the title:
Steps to reproduce: Craft a framed controller in the regular way, then frame it with whatever blocks you want, place, and attempt to break with any axe (tested with stone, iron, and diamond). Regardless of silk touch (tested with and without) the block will not drop. This applies to Framed Controllers, Framed Slaves, and Framed Trims.

https://github.com/Sirfirelord1/Petty-s-Cozycraft/issues/12

**Comment by eutro** [comment]
Thanks for the report. The bug was introduced in f3724dace1ad7ca92ed8ced24028c72830731d6f by the loot tables accidentally being moved, which I didn't notice because Storage Drawers doesn't actually use loot tables to compute _drawer_ drops. It should be fixed in 33736887c64209048e32a390a08bc912de2d9dda and thus the 1.20-6.0.1 release, which should be [here](https://www.curseforge.com/minecraft/mc-mods/framed-compacting-drawers/files/5284254) when it's approved.
